In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
DATA_FILE_PATH = "../data/Technical Assignment_Data_dev.xlsx"
SHEETS = ["Storage Report", "Product Details"]

In [3]:
df_storage_raw = pd.read_excel(DATA_FILE_PATH, sheet_name=SHEETS[0])
df_storage_raw.head()

,event label,date value,event line IU quantity,inventory unit (IU),event line HU quantity,handling unit (HU),event line weight (mT),event line volume (m3),event line value (USD),product category,product owner reference,product description
0,Opening Stock on Hand - Good Condition,2026-05-28,194688,Each,1352,Box/Carton,0.584,3.179,3759,Health,SMSUCOND1--;30/04/2029,"PRESERVATIF MASCULIN, lubrifié + RESERVOIR, u...."
1,Opening Stock on Hand - Good Condition,2026-05-28,5760,Each,40,Box/Carton,0.017,0.094,111,Health,SMSUCOND1;30/04/2029,"PRESERVATIF MASCULIN, lubrifié + RESERVOIR, u...."
2,Opening Stock on Hand - Good Condition,2026-05-28,16200,Each,162,Box/Carton,0.175,1.116,6642,Health,SMSUCONDF1-;30/04/2027,"PRESERVATIF FEMININ, lubrifié, 170 mm, u.u. (C..."
3,Opening Stock on Hand - Good Condition,2026-05-28,8064,Each,12,Box/Carton,0.008,0.039,156,Health,DORAPYRZ4T1;30/09/2027,"PYRAZINAMIDE [Z], 400 mg, comp., blister(OXALI..."
4,Opening Stock on Hand - Good Condition,2026-05-28,3000,Each,50,Box/Carton,0.005,0.071,2775,Health,DORARALT4T-;01/06/2027,"RALTEGRAVIR potassique [RAL], éq. 400 mg base,..."

In [4]:
df_product_details_raw = pd.read_excel(DATA_FILE_PATH, sheet_name=SHEETS[1])
df_product_details_raw.head()

,product_code,Description,Category,Sub-Category,Acronym,Monthly Consumption (# units)
0,DORAABLA1TD,"ABC 60 mg / 3TC 30 mg, comp. disp.",HIV,HIV / Paediatric,ABC+3TC,188356.363636
1,DORAYILN2T-,"AZT 300 mg / 3TC 150 mg / NVP 200 mg, comp.",HIV,HIV / Adults,AZT+3TC+NVP,613118.181818
2,DORAYILA2T-,"AZT 300 mg / 3TC 150 mg, comp.",HIV,HIV / Adults,AZT+3TC,704712.727273
3,DORAYILN1TD,"AZT 60 mg / 3TC 30 mg / NVP 50 mg, comp. dispe...",HIV,HIV / Paediatric,AZT+3TC+NVP,107056.363636
4,DORAYILA1TD,"AZT 60 mg / 3TC 30 mg, comp. disp.",HIV,HIV / Paediatric,AZT+3TC,40974.545455

In [5]:
df = (
    df_product_details_raw
    .pipe(lambda d: d[d.product_code.str.startswith("SMSUCOND")])
    .sort_values("product_code")
    #.query("product_code == 'SMSUCOND1'")
)
df.head()

Empty DataFrame
Columns: [product_code, Description, Category, Sub-Category, Acronym, Monthly Consumption (# units)]
Index: []

In [6]:
df_product_details = df_product_details_raw.rename(columns={
    "Description": "product_description",
    "Category": "product_category",
    "Sub-Category": "product_sub_category",
    "Acronym": "product_acronym",
    "Monthly Consumption (# units)": "monthly_consumption_in_units_per_month",
})
df_product_details.head()

,product_code,product_description,product_category,product_sub_category,product_acronym,monthly_consumption_in_units_per_month
0,DORAABLA1TD,"ABC 60 mg / 3TC 30 mg, comp. disp.",HIV,HIV / Paediatric,ABC+3TC,188356.363636
1,DORAYILN2T-,"AZT 300 mg / 3TC 150 mg / NVP 200 mg, comp.",HIV,HIV / Adults,AZT+3TC+NVP,613118.181818
2,DORAYILA2T-,"AZT 300 mg / 3TC 150 mg, comp.",HIV,HIV / Adults,AZT+3TC,704712.727273
3,DORAYILN1TD,"AZT 60 mg / 3TC 30 mg / NVP 50 mg, comp. dispe...",HIV,HIV / Paediatric,AZT+3TC+NVP,107056.363636
4,DORAYILA1TD,"AZT 60 mg / 3TC 30 mg, comp. disp.",HIV,HIV / Paediatric,AZT+3TC,40974.545455

In [7]:
df_storage_raw.head()

,event label,date value,event line IU quantity,inventory unit (IU),event line HU quantity,handling unit (HU),event line weight (mT),event line volume (m3),event line value (USD),product category,product owner reference,product description
0,Opening Stock on Hand - Good Condition,2026-05-28,194688,Each,1352,Box/Carton,0.584,3.179,3759,Health,SMSUCOND1--;30/04/2029,"PRESERVATIF MASCULIN, lubrifié + RESERVOIR, u...."
1,Opening Stock on Hand - Good Condition,2026-05-28,5760,Each,40,Box/Carton,0.017,0.094,111,Health,SMSUCOND1;30/04/2029,"PRESERVATIF MASCULIN, lubrifié + RESERVOIR, u...."
2,Opening Stock on Hand - Good Condition,2026-05-28,16200,Each,162,Box/Carton,0.175,1.116,6642,Health,SMSUCONDF1-;30/04/2027,"PRESERVATIF FEMININ, lubrifié, 170 mm, u.u. (C..."
3,Opening Stock on Hand - Good Condition,2026-05-28,8064,Each,12,Box/Carton,0.008,0.039,156,Health,DORAPYRZ4T1;30/09/2027,"PYRAZINAMIDE [Z], 400 mg, comp., blister(OXALI..."
4,Opening Stock on Hand - Good Condition,2026-05-28,3000,Each,50,Box/Carton,0.005,0.071,2775,Health,DORARALT4T-;01/06/2027,"RALTEGRAVIR potassique [RAL], éq. 400 mg base,..."

In [ ]:
df_storage = df_storage_raw.rename(columns={
    "event label": "event_label",
    "date value": "event_date",
    "event line IU quantity": "qty_inventory_unit",
    "inventory unit (IU)": "iu",
    "event line HU quantity": "qty_handling_unit",
    "handling unit (HU)": "handling_unit",
    "event line weight (mT)": "weight_mt",
    "event line volume (m3)": "volume_m3",
    "event line value (USD)": "value_usd",
    "product category": "product_category_storage",
    "product owner reference": "product_owner_ref_raw",
    "product description": "product_description_storage",
})

In [9]:
df_storage_raw.head(2)

,event label,date value,event line IU quantity,inventory unit (IU),event line HU quantity,handling unit (HU),event line weight (mT),event line volume (m3),event line value (USD),product category,product owner reference,product description
0,Opening Stock on Hand - Good Condition,2026-05-28,194688,Each,1352,Box/Carton,0.584,3.179,3759,Health,SMSUCOND1--;30/04/2029,"PRESERVATIF MASCULIN, lubrifié + RESERVOIR, u...."
1,Opening Stock on Hand - Good Condition,2026-05-28,5760,Each,40,Box/Carton,0.017,0.094,111,Health,SMSUCOND1;30/04/2029,"PRESERVATIF MASCULIN, lubrifié + RESERVOIR, u...."

In [ ]:
parsed = df_storage["product_owner_ref_raw"].str.split(";", expand=True)
df_storage["product_code"] = parsed[0].str.strip()
df_storage["expiry_date"] = pd.to_datetime(parsed[1].str.strip(), format="%d/%m/%Y", errors="coerce")

df_storage[["product_owner_ref_raw", "product_code", "expiry_date"]].head(10)

In [12]:
df_storage

,event_label,event_date,qty_inventory_unit,iu,qty_handling_unit,handling_unit,weight_mt,volume_m3,value_usd,product_category_storage,product_owner_ref_raw,product_description,product_code,expiry_date
0,Opening Stock on Hand - Good Condition,2026-05-28,194688,Each,1352,Box/Carton,0.584,3.179,3759,Health,SMSUCOND1--;30/04/2029,"PRESERVATIF MASCULIN, lubrifié + RESERVOIR, u....",SMSUCOND1--,2029-04-30
1,Opening Stock on Hand - Good Condition,2026-05-28,5760,Each,40,Box/Carton,0.017,0.094,111,Health,SMSUCOND1;30/04/2029,"PRESERVATIF MASCULIN, lubrifié + RESERVOIR, u....",SMSUCOND1,2029-04-30
2,Opening Stock on Hand - Good Condition,2026-05-28,16200,Each,162,Box/Carton,0.175,1.116,6642,Health,SMSUCONDF1-;30/04/2027,"PRESERVATIF FEMININ, lubrifié, 170 mm, u.u. (C...",SMSUCONDF1-,2027-04-30
3,Opening Stock on Hand - Good Condition,2026-05-28,8064,Each,12,Box/Carton,0.008,0.039,156,Health,DORAPYRZ4T1;30/09/2027,"PYRAZINAMIDE [Z], 400 mg, comp., blister(OXALI...",DORAPYRZ4T1,2027-09-30
4,Opening Stock on Hand - Good Condition,2026-05-28,3000,Each,50,Box/Carton,0.005,0.071,2775,Health,DORARALT4T-;01/06/2027,"RALTEGRAVIR potassique [RAL], éq. 400 mg base,...",DORARALT4T-,2027-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,Closing Stock on Hand - Good Condition,2026-05-28,528775,Each,21151,Box/Carton,6.345,19.228,89892,Health,SSDTMALP25T2;30/04/2028,"TEST MALARIA Pf [HRP-2] Ag RDT, st,1test [Care...",SSDTMALP25T2,2028-04-30
106,Closing Stock on Hand - Good Condition,2026-05-28,530875,Each,21235,Box/Carton,6.795,19.305,90249,Health,SSDTMALP25T2;30/04/2028,"TEST MALARIA Pf [HRP-2] Ag RDT, st,1test [Care...",SSDTMALP25T2,2028-04-30
107,Closing Stock on Hand - Good Condition,2026-05-28,526625,Each,21065,Box/Carton,6.741,19.150,89526,Health,SSDTMALP25T2;30/04/2028,"TEST MALARIA Pf [HRP-2] Ag RDT, st,1test [Care...",SSDTMALP25T2,2028-04-30
108,Closing Stock on Hand - Good Condition,2026-05-28,31350,Each,1254,Box/Carton,0.401,1.389,5330,Health,SSDTMALP25T2;30/04/2028,"TEST MALARIA Pf [HRP-2] Ag RDT, st,1test [Care...",SSDTMALP25T2,2028-04-30
109,Closing Stock on Hand - Good Condition,2026-05-28,5525,Each,221,Box/Carton,0.066,0.200,939,Health,SSDTMALP25T2;30/04/2028,"TEST MALARIA Pf [HRP-2] Ag RDT, st,1test [Care...",SSDTMALP25T2,2028-04-30

In [ ]:
df_storage = df_storage[
    [
        "product_code",
        "expiry_date",
        "qty_inventory_unit",
        "value_usd",
        "event_date",
        "event_label",
        "iu",
        "qty_handling_unit",
        "handling_unit",
        "weight_mt",
        "volume_m3",
        "product_description_storage",
        "product_category_storage",
        "product_owner_ref_raw",
    ]
].astype({
    "qty_inventory_unit": "Int64",
    "qty_handling_unit": "Int64",
    "value_usd": "Int64",
})

df_product_details = df_product_details[
    [
        "product_code",
        "product_category",
        "product_sub_category",
        "product_acronym",
        "product_description",
        "monthly_consumption_in_units_per_month",
    ]
]

In [19]:
# % valeurs manquantes par colonne
print("=== df_storage ===")
print((df_storage.isna().mean() * 100).round(1).to_string())
print()
print("=== df_product_details ===")
print((df_product_details.isna().mean() * 100).round(1).to_string())

=== df_storage ===
product_code                   0.0
expiry_date                    3.6
qty_inventory_unit             0.0
value_usd                      0.0
event_date                     0.0
event_label                    0.0
iu                             0.0
qty_handling_unit              0.0
handling_unit                  0.0
weight_mt                      0.0
volume_m3                      0.0
product_description_storage    0.0
product_category_storage       0.0
product_owner_ref_raw          0.0

=== df_product_details ===
product_code                              0.0
product_category                          0.0
product_sub_category                      0.0
product_acronym                           0.0
product_description                       0.0
monthly_consumption_in_units_per_month    0.0

In [20]:
# Références dans df_storage absentes de df_product_details
known_codes = set(df_product_details["product_code"])
mask_unknown = ~df_storage["product_code"].isin(known_codes)

unknown = df_storage[mask_unknown]
total = df_storage

summary = pd.DataFrame({
    "n_rows": [mask_unknown.sum(), len(df_storage)],
    "n_unique_codes": [unknown["product_code"].nunique(), total["product_code"].nunique()],
    "qty_inventory_unit": [unknown["qty_inventory_unit"].sum(), total["qty_inventory_unit"].sum()],
    "value_usd": [unknown["value_usd"].sum(), total["value_usd"].sum()],
}, index=["not in product_details", "total"])

summary["pct_qty"] = (summary["qty_inventory_unit"] / summary.loc["total", "qty_inventory_unit"] * 100).round(1)
summary["pct_value"] = (summary["value_usd"] / summary.loc["total", "value_usd"] * 100).round(1)

summary

,n_rows,n_unique_codes,qty_inventory_unit,value_usd,pct_qty,pct_value
not in product_details,60,14,8762776,775372,63.1,40.8
total,110,22,13895236,1900028,100.0,100.0

In [ ]:
df = df_storage.merge(df_product_details, on="product_code", how="left")
df.shape